"""
Structured Capability Artifact Schema.

================================================================================
ENGINEERING DESIGN CHOICES & TRADE-OFFS:
================================================================================
1. Contract-First vs. Raw Transcript:
   - Trade-off: Storing raw LLM reasoning transcripts is trivial but makes execution
     non-deterministic, brittle, and token-expensive.
   - Decision: Synthesize raw discovery runs into a strict, typed contract (CapabilityArtifact).
     This decouples capability consumption from the model, enabling zero-inference production
     replay and making the capability verifiable by human reviewers and calling agents.

2. Multi-Strategy Locator Bundles vs. Single Selectors:
   - Trade-off: CSS/XPath selectors break immediately on legacy enterprise apps where IDs
     are dynamically generated by server frameworks (e.g., ASP.NET ctl00$MainContent$...).
   - Decision: Bundle locators with a defined priority cascade:
       Primary: Semantic Accessibility Tree (role + accessible name)
       Fallback 1: Visible Text Anchors
       Fallback 2: Relational Table Structural Locators (row_match + column_header)
       Fallback 3: CSS / XPath
     Each locator records explicit `robustness_rationale` explaining why it survives UI drift.

3. Explicit Business Outcomes vs. Error Exceptions:
   - Trade-off: Raising exceptions on 'Record Not Found' treats legitimate business outcomes
     as infrastructure crashes.
   - Decision: Model expected domain states as first-class citizens (`BusinessOutcomeDeclaration`),
     returning structured domain codes (e.g., MEMBER_NOT_FOUND) instead of crashing the pipeline.
================================================================================
"""

from enum import Enum
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field


class ParameterType(str, Enum):
    STRING = "string"
    NUMBER = "number"
    INTEGER = "integer"
    BOOLEAN = "boolean"


class ActionType(str, Enum):
    NAVIGATE = "navigate"
    CLICK = "click"
    FILL = "fill"
    SELECT = "select"
    WAIT_FOR = "wait_for"
    EXTRACT = "extract"
    ASSERT = "assert"


class RiskClassification(str, Enum):
    """
    Risk taxonomy for financial operations under banking compliance (GLBA/SOX):
    - SAFE_REVERSIBLE: Read-only queries, navigation, non-submitting form entries.
    - RISKY_MUTATION: Form submissions that update customer non-financial metadata.
    - RISKY_IRREVERSIBLE: Wire releases, ledger debiting, account locks.
      Mandates dual-control supervisor authorization before execution.
    """
    SAFE_REVERSIBLE = "safe_reversible"
    RISKY_MUTATION = "risky_mutation"
    RISKY_IRREVERSIBLE = "risky_irreversible"


class LocatorType(str, Enum):
    AX_ROLE_NAME = "ax_role_name"                # Primary: Accessibility Tree (role + accessible name)
    TEXT_ANCHOR = "text_anchor"                  # Fallback 1: Visible text anchor
    TABLE_CELL = "table_cell"                    # Fallback 2: Structural table cell relative locator
    CSS_SELECTOR = "css_selector"                # Fallback 3: CSS selector
    XPATH = "xpath"                              # Fallback 4: XPath


class LocatorDefinition(BaseModel):
    strategy: LocatorType
    value: str
    role: Optional[str] = None                   # E.g. "textbox", "button", "tab", "row"
    name: Optional[str] = None                   # Accessible name or label
    parent_context: Optional[str] = None         # Container or table header anchor
    column_header: Optional[str] = None          # For table relative locators
    row_match: Optional[str] = None              # For table relative locators


class MultiStrategyLocator(BaseModel):
    """
    Robust locator bundle combining multiple complementary targeting strategies.
    Survives UI re-renders, framework styling updates, and table layout shifts.
    """
    primary: LocatorDefinition
    fallbacks: List[LocatorDefinition] = Field(default_factory=list)
    robustness_rationale: str = Field(
        ...,
        description="Engineering justification for why this locator strategy survives UI drift on legacy surfaces."
    )


class InputParameter(BaseModel):
    name: str
    type: ParameterType = ParameterType.STRING
    description: str
    required: bool = True
    default: Optional[Any] = None
    example: Optional[Any] = None


class OutputField(BaseModel):
    name: str
    type: ParameterType = ParameterType.STRING
    description: str
    target_locator: Optional[MultiStrategyLocator] = None
    extract_attribute: str = "inner_text"        # "inner_text", "value", or regex
    regex_pattern: Optional[str] = None


class RecoveryAction(BaseModel):
    """Encapsulates self-healing recovery rules for transient modals and interstitials."""
    condition_description: str
    detect_locator: MultiStrategyLocator
    dismiss_action: ActionType = ActionType.CLICK
    dismiss_locator: MultiStrategyLocator
    max_retries: int = 2


class CapabilityStep(BaseModel):
    step_id: str
    description: str
    action: ActionType
    target: Optional[MultiStrategyLocator] = None
    value_template: Optional[str] = None         # Parameterized mustache template e.g. "{{inputs.member_id}}"
    risk_level: RiskClassification = RiskClassification.SAFE_REVERSIBLE
    timeout_ms: int = 5000
    checkpoint_assertion: Optional[str] = None   # Verification predicate e.g. "url_contains:detail"
    known_recoveries: List[RecoveryAction] = Field(default_factory=list)


class BusinessOutcomeDeclaration(BaseModel):
    """
    Declares expected domain outcomes to distinguish legitimate business states from crashes.
    For example: 'Member Not Found (AC-404)' is a valid operational result that must be
    returned to the calling agent with structured metadata rather than failing the run.
    """
    outcome_code: str                            # E.g. "MEMBER_NOT_FOUND", "ACCOUNT_RESTRICTED"
    description: str
    detection_locator: MultiStrategyLocator
    text_pattern: str                            # Regex e.g. "AC-404: Member Record.*not found"
    mapped_return_status: str = "business_outcome"


class CheckpointAssertion(BaseModel):
    assertion_type: str                          # "text_contains", "element_visible", "url_contains"
    expected_value: str
    target: Optional[MultiStrategyLocator] = None


class CapabilityArtifact(BaseModel):
    """
    Typed, versioned capability artifact.
    Callable by AI agents in production without LLM re-reasoning.
    """
    schema_version: str = "1.0.0"
    capability_id: str                           # E.g. "apexcore.member.get_savings_balance"
    name: str
    version: str = "1.0.0"
    description: str
    target_app: str                              # E.g. "ApexCore Banking Servicing Console"
    entry_point_url: str                         # E.g. "http://127.0.0.1:8088/apexcore"
    inputs: Dict[str, InputParameter] = Field(default_factory=dict)
    outputs: Dict[str, OutputField] = Field(default_factory=dict)
    success_checkpoints: List[CheckpointAssertion] = Field(default_factory=list)
    business_outcomes: List[BusinessOutcomeDeclaration] = Field(default_factory=list)
    steps: List[CapabilityStep] = Field(default_factory=list)
    created_at: Optional[str] = None
    created_by: str = "AutonomousDiscoveryAgent/1.0"
    tags: List[str] = Field(default_factory=list)


def serialize_artifact(model: BaseModel, indent: int = 2) -> str:
    """Serialize Pydantic model with cross-version v1/v2 compatibility."""
    if hasattr(model, "model_dump_json"):
        return model.model_dump_json(indent=indent)
    return model.json(indent=indent)


def deserialize_artifact(json_str: str) -> CapabilityArtifact:
    """Deserialize CapabilityArtifact with cross-version v1/v2 compatibility."""
    if hasattr(CapabilityArtifact, "model_validate_json"):
        return CapabilityArtifact.model_validate_json(json_str)
    return CapabilityArtifact.parse_raw(json_str)


def model_to_dict(model: BaseModel) -> Dict[str, Any]:
    """Convert Pydantic model to dict with cross-version v1/v2 compatibility."""
    if hasattr(model, "model_dump"):
        return model.model_dump()
    return model.dict()
